import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  gettingStartedSidebar: [
    { type: 'doc', id: 'getting-started', label: 'Getting Started' },
    { type: 'doc', id: 'core', label: 'Core' },
    { type: 'doc', id: 'googlemaps', label: 'GoogleMaps' },
    { type: 'doc', id: 'openstreetmap', label: 'OpenStreetMap' },
    { type: 'doc', id: 'mapbox', label: 'Mapbox' },
    { type: 'doc', id: 'azuremaps', label: 'AzureMaps' },
    { type: 'doc', id: 'apple', label: 'Apple' },
  ],
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
  advancedUsageSidebar: [{ type: 'autogenerated', dirName: 'advanced-usage' }],
  contributingSidebar: [
    { type: 'doc', id: 'contributing', label: 'Contributing' },
    { type: 'doc', id: 'sample-app', label: 'Sample App' },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
