name: CD

on:
  push:
    branches:
      - main
      - ci/sample-app-publishing

jobs:
  sample-app-android:
    runs-on: ubuntu-latest

    env:
      TURBO_CACHE_DIR: .turbo/android
      APK_PATH: sample-app/android/app/build/outputs/apk/debug/app-debug.apk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Cache turborepo for Android
        uses: actions/cache@v3
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turborepo-android-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-turborepo-android-

      - name: Check turborepo cache for Android
        run: |
          TURBO_CACHE_STATUS=$(node -p "($(yarn turbo run build:android --cache-dir="${{ env.TURBO_CACHE_DIR }}" --dry=json)).tasks.find(t => t.task === 'build:android').cache.status")

          if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
            echo "turbo_cache_hit=1" >> $GITHUB_ENV
          fi

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Finalize Android SDK
        if: env.turbo_cache_hit != 1
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Cache Gradle
        if: env.turbo_cache_hit != 1
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('sample-app/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build example for Android
        env:
          JAVA_OPTS: '-XX:MaxHeapSize=6g'
        run: |
          yarn turbo run build:android --cache-dir="${{ env.TURBO_CACHE_DIR }}"

      # Publishes the app to App Center
      - name: Publish app to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ secrets.APP_CENTER_APP_NAME }}
          group: ${{ secrets.APP_CENTER_GROUP }}
          token: ${{ secrets.APP_CENTER_TOKEN }}
          file: ${{ env.APK_PATH }}
          notifyTesters: true
          debug: true
          gitReleaseNotes: true

  # sample-app-ios:
  #   runs-on: macos-14
  #   env:
  #     TURBO_CACHE_DIR: .turbo/ios
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup
  #       uses: ./.github/actions/setup

  #     - name: Cache turborepo for iOS
  #       uses: actions/cache@v3
  #       with:
  #         path: ${{ env.TURBO_CACHE_DIR }}
  #         key: ${{ runner.os }}-turborepo-ios-${{ hashFiles('yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-turborepo-ios-

  #     - name: Check turborepo cache for iOS
  #       run: |
  #         TURBO_CACHE_STATUS=$(node -p "($(yarn turbo run build:ios --cache-dir="${{ env.TURBO_CACHE_DIR }}" --dry=json)).tasks.find(t => t.task === 'build:ios').cache.status")

  #         if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
  #           echo "turbo_cache_hit=1" >> $GITHUB_ENV
  #         fi

  #     - name: Cache cocoapods
  #       if: env.turbo_cache_hit != 1
  #       id: cocoapods-cache
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           **/ios/Pods
  #         key: ${{ runner.os }}-cocoapods-${{ hashFiles('sample-app/ios/Podfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-cocoapods-

  #     - name: Install cocoapods
  #       if: env.turbo_cache_hit != 1 && steps.cocoapods-cache.outputs.cache-hit != 'true'
  #       run: |
  #         cd sample-app/ios
  #         pod install
  #       env:
  #         NO_FLIPPER: 1

  #     - name: Build example for iOS
  #       run: |
  #         yarn turbo run build:ios --cache-dir="${{ env.TURBO_CACHE_DIR }}"
