name: CI

on:
  pull_request:
    branches: [main, develop, 'release/**']
    types: [opened, synchronize]

jobs:
  # this job sets up the dependencies in the monorepo & caches them and runs first
  # which speeds up the other jobs, as they will use the cached node_modules
  setup-monorepo:
    name: Setup monorepo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

  lint:
    needs: setup-monorepo
    name: Lint & typecheck files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    needs: setup-monorepo
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage

  build-packages:
    needs: setup-monorepo
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build packages
        run: yarn build:packages
